// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBim2mmR1KYb4K4Drv_FKmeOxzDtHCd_cA',
    appId: '1:732138783615:web:8c752bc8e29aa74d5b504a',
    messagingSenderId: '732138783615',
    projectId: 'awesome-to-do-app-45e6d',
    authDomain: 'awesome-to-do-app-45e6d.firebaseapp.com',
    storageBucket: 'awesome-to-do-app-45e6d.appspot.com',
    measurementId: 'G-81BQLD232D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo-xESNqy7fw_oZlS4cGRoJp6Bu0PXw4U',
    appId: '1:732138783615:android:040b49f93e3153da5b504a',
    messagingSenderId: '732138783615',
    projectId: 'awesome-to-do-app-45e6d',
    storageBucket: 'awesome-to-do-app-45e6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrqO4CLOZi8FxPQ46cug3OHQki6syY-Ao',
    appId: '1:732138783615:ios:2b65cc67e20ac0495b504a',
    messagingSenderId: '732138783615',
    projectId: 'awesome-to-do-app-45e6d',
    storageBucket: 'awesome-to-do-app-45e6d.appspot.com',
    iosClientId: '732138783615-1v328i9c2mk40l9tjui26lfarp1b6da5.apps.googleusercontent.com',
    iosBundleId: 'com.example.awesomeToDoApp',
  );
}
